### PR TITLE
fix: :bug: ctx.data is now typed to responseTransformer

### LINKED ISSUE #6: @typescript-eslint/no-unsafe-argument
**Describe the bug**

The examples fails to adhere to this typescript eslint rules
https://typescript-eslint.io/rules/no-unsafe-argument/

**To Reproduce**
add this `.eslintrc.json` to the root of this repository
```json
{
  "overrides": [
    {
      "extends": [
        "plugin:@typescript-eslint/recommended-requiring-type-checking"
      ],
      "files": ["*.ts", "*.tsx"],
      "parserOptions": {
        "project": "tsconfig.json"
      }
    }
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json"
  },
  "plugins": ["@typescript-eslint"],
  "extends": ["plugin:@typescript-eslint/recommended"]
}
```
run `eslint test/integration.test.js`
There will be error:
```
  12:35  error  Unsafe argument of type `any` assigned to a parameter of type `ResponseTransformer<DefaultBodyType, any>`  @typescript-eslint/no-unsafe-argument
  15:35  error  Unsafe argument of type `any` assigned to a parameter of type `ResponseTransformer<DefaultBodyType, any>`  @typescript-eslint/no-unsafe-argument
  18:35  error  Unsafe argument of type `any` assigned to a parameter of type `ResponseTransformer<any, any>`              @typescript-eslint/no-unsafe-argument
  21:35  error  Unsafe argument of type `any` assigned to a parameter of type `ResponseTransformer<DefaultBodyType, any>`  @typescript-eslint/no-unsafe-argument
  24:35  error  Unsafe argument of type `any` assigned to a parameter of type `ResponseTransformer<DefaultBodyType, any>`  @typescript-eslint/no-unsafe-argument
  27:35  error  Unsafe argument of type `any` assigned to a parameter of type `ResponseTransformer<any, any>`              @typescript-eslint/no-unsafe-argument
```

**Expected behavior**

There should be no error.

### PR DESCRIPTION
**Pull request by CUexter**
Closes #6

## 🎯 Changes

What changes are made in this PR? Is it a feature or a bug fix?
ctx.data now returns responseTransformer 
## ✅ Checklist

- [ ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by maloguertin** [comment]
Thanks for your PR! I'll try to look at it later today.

**Comment by maloguertin** [comment]
Nice one @CUexter do you think you could add a test for that?

**Comment by CUexter** [comment]
How do I test that ?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by CUexter** [comment]
i will try to investigate on how to do testing on next week

**Comment by Anerco** [comment]
any updates on this?

**Comment by CUexter** [comment]
idk how to work on this. Should i add eslint to this repo ? Cause originally i was having this issue. Of coz i can always assert the type, but that seems useless @maloguertin

**Comment by maloguertin** [comment]
Take a look at my PR and tell me if that works for you! https://github.com/maloguertin/msw-trpc/pull/7

**Pull request merged**
